ENABLE_LINTERS:
  - "MARKDOWN_MARKDOWNLINT"
  - "MARKDOWN_REMARK_LINT"
  - "MARKDOWN_MARKDOWN_LINK_CHECK"
  - "MARKDOWN_MARKDOWN_TABLE_FORMATTER"
MARKDOWN_MARKDOWN_LINK_CHECK_FILTER_REGEX_INCLUDE: (\*localhost*)
EXCLUDED_DIRECTORIES:
  - "/book"
  - "/.github"
