ENABLE_LINTERS:
  - "MARKDOWN_MARKDOWNLINT"
  - "MARKDOWN_REMARK_LINT"
  - "MARKDOWN_MARKDOWN_LINK_CHECK"
MARKDOWN_MARKDOWN_LINK_CHECK_FILTER_REGEX_INCLUDE: (\*localhost*)
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_INCLUDE: (\*SUMMARY*)
EXCLUDED_DIRECTORIES:
  - "/book"
  - "/.github"
