name: GitHub Pages

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install mdBook
        run: cargo install mdbook
      - name: Build
        run: mdbook build
      - uses: chdalski/github-actions/github-pages@main
        with:
          deploy_dir: book
          github_token: "${{ secrets.gh_pages_token }}"
